sudo: required
language:
- ruby

services:
# - docker
- mysql

before_install:
- if [ ! -f Campaign_Template1.mdb ]; then
    wget "http://www.arialsoftware.com/uploads/9/1/8/3/9183466/campaign_template1.zip"
    && unzip campaign_template1.zip
    && rm campaign_template1.zip;
  fi
- sudo apt-get -qq update && sudo apt-get -qq -y install mdbtools # mysql-client # already available on travis: mysql-client

# https://hub.docker.com/_/mysql/
#- docker run -d
#  -p 3306:3306
#  -e MYSQL_RANDOM_ROOT_PASSWORD=yes
#  -e MYSQL_USER=$MYSQL_USER
#  -e MYSQL_PASSWORD=$MYSQL_PASSWORD
#  -e MYSQL_DATABASE=$MYSQL_DATABASE
#  mysql:8
#
# more options
##   -e MYSQL_ALLOW_EMPTY_PASSWORD
##  -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

before_script:
- mysql -e "create database $MYSQL_DATABASE"
# - sleep 30 # wait till mysql server is done initializing
- bash MDBtoMySQL.sh
  -m Campaign_Template.mdb
  -d $MYSQL_DATABASE
  -u $MYSQL_USER
  -p $MYSQL_PASSWORD
  -h 127.0.0.1
  -g acc_monitor_log # CHECKINOUT

script:
- res1=`
  mysql --host=127.0.0.1
        --user=$MYSQL_USER
        --password=$MYSQL_PASSWORD
        $MYSQL_DATABASE
        -e "select count(*) from information_schema.TABLES where TABLE_NAME='Campaign_Table'"
        -BN 2>/dev/null
  `
- test "$res1" == "1"
- res2=`
  mysql --host=127.0.0.1
        --user=$MYSQL_USER
        --password=$MYSQL_PASSWORD
        $MYSQL_DATABASE
        -e "select count(*) from Campaign_Table"
        -BN 2>/dev/null
  `
- test "$res2" == "0"

after_success:
- docker ps|grep mysql|awk '{print "docker stop " $1}'|bash

#  - MYSQL_ROOT_PASSWORD=my-secret-pw
env:
  global:
  - MYSQL_USER=root
  - MYSQL_PASSWORD=""
  - MYSQL_DATABASE=movies

branches:
  only:
  - develop
